project:
  type: website
  output-dir: docs

website:
  title: "JM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 01_edge.qmd
        text: Edge AI
      - href: 02_cloud.qmd
        text: Cloud
      - href: 03_data.qmd
        text: Data
    right:
      - icon: github
        href: https://github.com/Najo1on1
      - icon: linkedin
        href: https://www.linkedin.com/in/muwanguzi-jonathan-a0b766124/
  
  page-footer:
    center: "Â© 2026 Jonathan Muwanguzi. Built with Quarto."

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css
    toc: true
    smooth-scroll: true
    lightbox: auto