project:
  type: website
  output-dir: docs

website:
  title: "Jonathan Muwanguzi | AI & Cloud Engineer"
  
  navbar:
    left:
      - text: "Competency Dashboard"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/Najo1on1
      - icon: linkedin
        href: https://www.linkedin.com/in/muwanguzi-jonathan-a0b766124/
  page-footer:
    center: "Â© 2026 Jonathan Muwanguzi. Built with Quarto."

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    toc: true
    smooth-scroll: true
    css: styles.css
    lightbox: auto